name: Build

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-vapoursynth
            mingw-w64-ucrt-x86_64-libjpeg-turbo
            mingw-w64-ucrt-x86_64-libpng
            mingw-w64-ucrt-x86_64-lcms2
      - name: Build
        run: |
          CXX="c++" meson setup build --prefer-static -Dcpp_link_args='-static'
          meson compile -C build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: carefulsource-windows
          path: |
            build/libcarefulsource.dll
